/*ALTER TABLE inventory MODIFY COLUMN details VARCHAR(30) NOT NULL;
ALTER TABLE inventory MODIFY COLUMN quantity INT NOT NULL;
ALTER TABLE inventory MODIFY COLUMN imageurl VARCHAR(50) NOT NULL;
ALTER TABLE inventory MODIFY COLUMN is_deleted TINYINT(1) NOT NULL;